### PR TITLE
Update README.md

### LINKED ISSUE #29: Possibly compatible with GitLens and other decorators
Thank you for Render-CRLF, Josip.

1. Please have a look at https://github.com/microsoft/vscode/issues/33852. It sounds like the conflicts with GitLens etc. may be gone. (I can't confirm, I don't use them).
2. If the problem still exists, please check the Markdown of the link to https://github.com/microsoft/vscode/issues/33852 from README.md. On GitHub it renders OK. But on https://marketplace.visualstudio.com/items?itemName=medo64.render-crlf it renders bad: `[issue [#33852](https://github.com/medo64/render-crlf/issues/33852)](https://github.com/microsoft/vscode/issues/33852)`, and, even worse, the first part is a link to a non-existing issue number `33852` in this (Render-CRLF) repo.

### PR DESCRIPTION
**Pull request by its-miroma**
Update README.md structure

Fixes #29

### CODE REVIEW

**Comment by its-miroma** [comment]
Please let me know if there's anything I should change

**Comment by medo64** [comment]
Hi again, thank you for all updates! They look good!

However., I wonder if there is a reason for changing ICON.png and ICON.svg to lowercase? I think I prefer them uppercase (so they match README, LICENSE, etc.)

Also, I notice that new screenshots are on the large side so they don't fit with README.md nicely. It's not a deal breaker for this PR as I can always reduce their size later.

**Comment by its-miroma** [comment]
Many other extensions have `icon.png` in lowercase, and actually most
of them place `icon.png` in `images/`:
- https://github.com/usernamehw/vscode-error-lens/blob/972ea1f680578ad7ef40756b738e8dd15d76f502/package.json#L32
- https://github.com/DavidAnson/vscode-markdownlint/blob/0a6d31287999d933477cf3e5102c7e1344f5c8e6/package.json#L5
- https://github.com/redhat-developer/vscode-yaml/blob/e5a67a112a9a52eb8d8c991bf444fb309b2eb913/package.json#L24

It's not a problem though, I can change it back if you want.

I've also scaled down the image, as I'd forgotten to do that earlier.

**Comment by medo64** [comment]
I decided to split the baby :)
I moved icon.png to images where it can be independently sized and returned ICON.png since I have some tools dependent on it (I know, I need better tools :))

**Comment by its-miroma** [comment]
Could you also please update this GitHub repo description?
You can adapt the first line from `README.md`:
``This VS Code extension renders end of line characters (CR, LF, CRLF) when whitespace rendering is on.``

**Comment by medo64** [comment]
Sure, updated. Albeit I kicked the CR out as upstream still doesn't support it.

**Pull request merged**
